language: python
python:
  - 2.6
  - 2.7
  - pypy
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential libssl-dev swig python-m2crypto python-numpy
  - pip install m2crypto salsa20 shadowsocks
script:
  - sudo python test.py -c tests/table.json
  - sudo python test.py -c tests/aes.json
